Fix for thing actions without @ActionInput
seaside1/jrule pull request #143
Opened 2023-03-21 20:14 UTC by seime

Partial fix for #142 .

Missing: Compilation of generated code relies only on openhab-core and jrule jar, and due to https://github.com/openhab/openhab-addons/blob/8e902f63243a11e2dd9898fade150312184aa23c/bundles/org.openhab.binding.dbquery/src/main/java/org/openhab/binding/dbquery/action/DBQueryActions.java#L49 returning `ActionQueryResult`from dbquery https://github.com/openhab/openhab-addons/blob/8e902f63243a11e2dd9898fade150312184aa23c/bundles/org.openhab.binding.dbquery/src/main/java/org/openhab/binding/dbquery/action/ActionQueryResult.java#L13 compilation fails.

Not sure what to do here; either include all openhab jars as classpath (including addons) - or replicate class dynamically?
@querdenker2k  WDYT?

2023-03-22 20:32 UTC, seaside1 commented
I really would prefer if we keep dependencies at a minimum. It will be more difficult to develop rules when a lot of different dependencies. One option could be to generate a fat jar which includes all needed deps, but not sure it the right approach.

2023-03-29 19:25 UTC, seaside1 commented
What should we do about this then? Merge and later sort out how to handle deps?

2023-03-30 12:20 UTC, seime commented
Well we do now have an incompatibility with the `dbquery` binding. Possibly others.

A workaround for now could also be to ignore action methods that rely on external classes. No actions would be generated for those, but at least it should not break everything.

2023-03-30 14:59 UTC, querdenker2k commented
I am still on vacation, but there was already implemented to support internal openhab types. But I don't know which binding it was. I assume it was the hue binding but I am not using it, maybe one of you?

2023-03-30 17:07 UTC, seime commented
Good catch. I'm now only filtering anything that isnt a primitive, a `java.*` class or a type in the openhab type package.

2023-04-02 19:35 UTC, querdenker2k approved these changes
working for me

2023-04-02 19:35 UTC, querdenker2k commented
there's still a conflict

2023-04-02 20:00 UTC, querdenker2k commented
for the final resolution:
- replaceing the class could be hard because of other dependent classes -> i think this is not a option
- another option would be to just return Object for addon-specific types
- what if we add all openhab jars (including addons as seime suggested) and generate a pom snippet (and logs) as well with the required jars (programmatically the action parameters/return types will be searched in all openhab addon jars)

2023-04-13 08:07 UTC, seime commented
@querdenker2k liked option 2 -> map to java.lang.Object. The user can add the binding to its own rule project and do necessary casting

2023-04-13 19:02 UTC, querdenker2k requested changes

2023-04-13 19:02 UTC, querdenker2k commented on src/main/java/org/openhab/automation/jrule/actions/JRuleActionClassGenerator.java
> +                                        "ActionInput not set on action method parameter").name());
this can never occur (ActionInput = null), because it's checked 6 lines before.

2023-04-14 18:53 UTC, querdenker2k approved these changes

2023-04-15 12:34 UTC, merged